### ISSUE TITLE
No such file <path>/node_modules/es5-ext/array/index.js#/uniq.js

### ISSUE THREAD

**Issue by guicattani** [azu/express-router-dependency-graph#2]
Hey azu!

Sorry if this is a newbie question, I'm new to Node!
I can't run `express-router-dependency-graph` neither installing globally with `npm install express-router-dependency-graph -g` nor with executing via npx: `npx express-router-dependency-graph --rootDir=/home/user/Documents/project`

What I get is:

```bash
Error: Extracting dependencies ran afoul of...

  ENOENT: no such file or directory, open '/home/user/Documents/project/node_modules/es5-ext/array/index.js#/uniq.js'
... in node_modules/es5-ext/array/index.js#/uniq.js


    at getDependencies (/home/user/.nvm/versions/node/v16.0.0/lib/node_modules/express-router-dependency-graph/node_modules/dependency-cruiser/src/extract/get-dependencies.js:208:11)
    at extractRecursive (/home/user/.nvm/versions/node/v16.0.0/lib/node_modules/express-router-dependency-graph/node_modules/dependency-cruiser/src/extract/index.js:20:9)
    at lDependencies.filter.reduce.source (/home/user/.nvm/versions/node/v16.0.0/lib/node_modules/express-router-dependency-graph/node_modules/dependency-cruiser/src/extract/index.js:36:13)
    at Array.reduce (<anonymous>)
    at extractRecursive (/home/user/.nvm/versions/node/v16.0.0/lib/node_modules/express-router-dependency-graph/node_modules/dependency-cruiser/src/extract/index.js:32:6)
    at lDependencies.filter.reduce.source (/home/user/.nvm/versions/node/v16.0.0/lib/node_modules/express-router-dependency-graph/node_modules/dependency-cruiser/src/extract/index.js:36:13)
    at Array.reduce (<anonymous>)
    at extractRecursive (/home/user/.nvm/versions/node/v16.0.0/lib/node_modules/express-router-dependency-graph/node_modules/dependency-cruiser/src/extract/index.js:32:6)
    at /home/user/.nvm/versions/node/v16.0.0/lib/node_modules/express-router-dependency-graph/node_modules/dependency-cruiser/src/extract/index.js:80:9
    at Array.reduce (<anonymous>)
```

but es5-ext is installed in node_modules and the path is like this:
![image](https://user-images.githubusercontent.com/13826108/116818833-be5f3080-ab43-11eb-9805-baf7b49ab780.png)

Here are the dependencies of this project:

```json
"dependencies": {
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "express": "^4.17.1",
    "express-validator": "^6.10.0",
    "passport": "^0.4.1",
    "pg": "^8.6.0",
    "sequelize": "^6.6.2"
  },
  "devDependencies": {
    "express-router-dependency-graph": "1.0.0",
    "nodemon": "^2.0.7",
    "prettier": "^2.2.1",
    "sequelize-cli": "^6.2.0"
  }
```

Any tips? Am I doing something wrong here?
Thanks a lot :)

**Comment by azu** [comment]
> ```shell
>   ENOENT: no such file or directory, open '/home/user/Documents/project/node_modules/es5-ext/array/index.js#/uniq.js'
> ```

Fmm, `node_modules/es5-ext/array/#/uniq.js` is the correct path. 
`index.js#` is something wrong.
I think that this is [dependency-cruiser](https://github.com/sverweij/dependency-cruiser)'s bug.

I've added a workaround and release <https://github.com/azu/express-router-dependency-graph/releases/tag/v1.0.5>

**Comment by azu** [comment]
I've reported the bug to dependency-cruiser.
https://github.com/sverweij/dependency-cruiser/issues/459
